import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';

export async function generateTripPDF(trip: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const buffers: Buffer[] = [];

    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      const pdfData = Buffer.concat(buffers);
      resolve(pdfData);
    });
    doc.on('error', reject);

    // Header
    doc.fontSize(24).font('Helvetica-Bold').text(trip.title, { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(12).font('Helvetica').text(`${trip.city} | ${new Date(trip.dateStart).toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(1);

    // Trip Details
    doc.fontSize(10);
    doc.text(`Group Size: ${trip.groupSizeMin}-${trip.groupSizeMax} people`);
    doc.text(`Occasion: ${trip.occasion}`);
    doc.text(`Budget Level: ${trip.budgetLevel}`);
    doc.moveDown(1.5);

    // Itinerary
    doc.fontSize(18).font('Helvetica-Bold').text('Itinerary');
    doc.moveDown(0.5);

    const events = trip.events || [];
    events.forEach((event: any, index: number) => {
      doc.fontSize(14).font('Helvetica-Bold').text(`${index + 1}. ${event.title}`);
      doc.fontSize(10).font('Helvetica');

      const startTime = new Date(event.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      const endTime = new Date(event.endTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

      doc.text(`Time: ${startTime} - ${endTime}`);
      doc.text(`Type: ${event.type}`);

      if (event.venue) {
        doc.text(`Venue: ${event.venue.name}`);
        doc.text(`Address: ${event.venue.address}`);
        if (event.venue.phone) {
          doc.text(`Phone: ${event.venue.phone}`);
        }
      }

      if (event.description) {
        doc.text(`Details: ${event.description}`);
      }

      doc.moveDown(1);
    });

    // Footer
    doc.fontSize(8).text('Generated by PartyPilot', 50, doc.page.height - 50, { align: 'center' });

    doc.end();
  });
}
