import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const NYC_VENUES = [
  // RESTAURANTS - ITALIAN
  {
    name: 'Carbone',
    address: '181 Thompson St, New York, NY 10012',
    city: 'NYC',
    lat: 40.7272,
    lng: -74.0023,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/carbone',
    phone: '(212) 254-3000',
    website: 'https://carbonenewyork.com',
    rating: 4.6,
    priceLevel: '$$$$',
    dressCodeSummary: 'Smart casual to business casual',
    groupFriendly: true,
  },
  {
    name: 'L\'Artusi',
    address: '228 W 10th St, New York, NY 10014',
    city: 'NYC',
    lat: 40.7341,
    lng: -74.0047,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/lartusi',
    phone: '(212) 255-5757',
    website: 'https://lartusi.com',
    rating: 4.5,
    priceLevel: '$$$',
    dressCodeSummary: 'Casual to smart casual',
    groupFriendly: true,
  },
  {
    name: 'Via Carota',
    address: '51 Grove St, New York, NY 10014',
    city: 'NYC',
    lat: 40.7333,
    lng: -74.0039,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/via-carota',
    phone: '(212) 255-1962',
    website: 'https://www.viacarota.com',
    rating: 4.7,
    priceLevel: '$$',
    dressCodeSummary: 'Casual',
    groupFriendly: false,
  },
  {
    name: 'Don Angie',
    address: '103 Greenwich Ave, New York, NY 10014',
    city: 'NYC',
    lat: 40.7370,
    lng: -74.0009,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/don-angie',
    phone: '(212) 889-8884',
    website: 'https://www.donangie.com',
    rating: 4.6,
    priceLevel: '$$$',
    dressCodeSummary: 'Smart casual',
    groupFriendly: true,
  },
  {
    name: 'Il Mulino',
    address: '86 W 3rd St, New York, NY 10012',
    city: 'NYC',
    lat: 40.7304,
    lng: -74.0012,
    bookingType: 'api',
    bookingProvider: 'opentable',
    bookingUrl: 'https://www.opentable.com/r/il-mulino-new-york',
    phone: '(212) 673-3783',
    website: 'https://www.ilmulino.com',
    rating: 4.4,
    priceLevel: '$$$$',
    dressCodeSummary: 'Business casual to dressy',
    groupFriendly: true,
  },

  // RESTAURANTS - STEAKHOUSES
  {
    name: 'Peter Luger Steak House',
    address: '178 Broadway, Brooklyn, NY 11211',
    city: 'NYC',
    lat: 40.7107,
    lng: -73.9624,
    bookingType: 'deeplink',
    bookingProvider: 'custom',
    bookingUrl: 'https://www.peterluger.com/reservations',
    phone: '(718) 387-7400',
    website: 'https://www.peterluger.com',
    rating: 4.5,
    priceLevel: '$$$$',
    dressCodeSummary: 'Smart casual',
    groupFriendly: true,
  },
  {
    name: 'Wolfgang\'s Steakhouse',
    address: '4 Park Ave, New York, NY 10016',
    city: 'NYC',
    lat: 40.7465,
    lng: -73.9812,
    bookingType: 'api',
    bookingProvider: 'opentable',
    bookingUrl: 'https://www.opentable.com/r/wolfgangs-steakhouse-park-avenue-new-york',
    phone: '(212) 889-3369',
    website: 'https://wolfgangssteakhouse.net',
    rating: 4.4,
    priceLevel: '$$$$',
    dressCodeSummary: 'Business casual',
    groupFriendly: true,
  },
  {
    name: 'Quality Meats',
    address: '57 W 58th St, New York, NY 10019',
    city: 'NYC',
    lat: 40.7645,
    lng: -73.9755,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/quality-meats',
    phone: '(212) 371-7777',
    website: 'https://www.qualitymeatsnyc.com',
    rating: 4.5,
    priceLevel: '$$$$',
    dressCodeSummary: 'Smart casual to business casual',
    groupFriendly: true,
  },

  // RESTAURANTS - JAPANESE & SUSHI
  {
    name: 'COTE Korean Steakhouse',
    address: '16 W 22nd St, New York, NY 10010',
    city: 'NYC',
    lat: 40.7404,
    lng: -73.9905,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/cote',
    phone: '(212) 401-7986',
    website: 'https://www.cotenyc.com',
    rating: 4.7,
    priceLevel: '$$$$',
    dressCodeSummary: 'Smart casual',
    groupFriendly: true,
  },
  {
    name: 'Nobu Downtown',
    address: '195 Broadway, New York, NY 10007',
    city: 'NYC',
    lat: 40.7103,
    lng: -74.0098,
    bookingType: 'api',
    bookingProvider: 'opentable',
    bookingUrl: 'https://www.opentable.com/r/nobu-downtown-new-york',
    phone: '(212) 219-0500',
    website: 'https://www.noburestaurants.com',
    rating: 4.5,
    priceLevel: '$$$$',
    dressCodeSummary: 'Business casual to dressy',
    groupFriendly: true,
  },
  {
    name: 'Zuma',
    address: '261 Madison Ave, New York, NY 10016',
    city: 'NYC',
    lat: 40.7496,
    lng: -73.9810,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/zuma',
    phone: '(212) 544-7800',
    website: 'https://www.zumarestaurant.com',
    rating: 4.6,
    priceLevel: '$$$$',
    dressCodeSummary: 'Smart casual to business casual',
    groupFriendly: true,
  },

  // RESTAURANTS - AMERICAN & CONTEMPORARY
  {
    name: 'The Smith',
    address: '956 2nd Ave, New York, NY 10022',
    city: 'NYC',
    lat: 40.7601,
    lng: -73.9654,
    bookingType: 'api',
    bookingProvider: 'opentable',
    bookingUrl: 'https://www.opentable.com/r/the-smith-midtown-new-york',
    phone: '(212) 644-2700',
    website: 'https://www.thesmithrestaurant.com',
    rating: 4.3,
    priceLevel: '$$',
    dressCodeSummary: 'Casual',
    groupFriendly: true,
  },
  {
    name: 'Gramercy Tavern',
    address: '42 E 20th St, New York, NY 10003',
    city: 'NYC',
    lat: 40.7386,
    lng: -73.9881,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/gramercy-tavern',
    phone: '(212) 477-0777',
    website: 'https://www.gramercytavern.com',
    rating: 4.6,
    priceLevel: '$$$$',
    dressCodeSummary: 'Smart casual to business casual',
    groupFriendly: true,
  },
  {
    name: 'Union Square Cafe',
    address: '101 E 19th St, New York, NY 10003',
    city: 'NYC',
    lat: 40.7374,
    lng: -73.9879,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/union-square-cafe',
    phone: '(212) 243-4020',
    website: 'https://www.unionsquarecafe.com',
    rating: 4.5,
    priceLevel: '$$$',
    dressCodeSummary: 'Smart casual',
    groupFriendly: true,
  },

  // BARS - COCKTAIL & SPEAKEASY
  {
    name: 'PDT (Please Don\'t Tell)',
    address: '113 St Marks Pl, New York, NY 10009',
    city: 'NYC',
    lat: 40.7273,
    lng: -73.9850,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/pdt',
    phone: '(212) 614-0386',
    website: 'https://www.pdtnyc.com',
    rating: 4.6,
    priceLevel: '$$$',
    dressCodeSummary: 'Casual to smart casual',
    groupFriendly: false,
  },
  {
    name: 'Death & Company',
    address: '433 E 6th St, New York, NY 10009',
    city: 'NYC',
    lat: 40.7250,
    lng: -73.9807,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/death-and-company',
    phone: '(212) 388-0882',
    website: 'https://www.deathandcompany.com',
    rating: 4.7,
    priceLevel: '$$$',
    dressCodeSummary: 'Smart casual',
    groupFriendly: false,
  },
  {
    name: 'Employees Only',
    address: '510 Hudson St, New York, NY 10014',
    city: 'NYC',
    lat: 40.7346,
    lng: -74.0058,
    bookingType: 'deeplink',
    bookingProvider: 'custom',
    bookingUrl: 'https://www.employeesonlynyc.com',
    phone: '(212) 242-3021',
    website: 'https://www.employeesonlynyc.com',
    rating: 4.6,
    priceLevel: '$$$',
    dressCodeSummary: 'Smart casual',
    groupFriendly: true,
  },
  {
    name: 'Attaboy',
    address: '134 Eldridge St, New York, NY 10002',
    city: 'NYC',
    lat: 40.7208,
    lng: -73.9903,
    bookingType: 'manual',
    bookingProvider: null,
    bookingUrl: null,
    phone: null,
    website: null,
    rating: 4.7,
    priceLevel: '$$$',
    dressCodeSummary: 'Casual to smart casual',
    groupFriendly: false,
  },
  {
    name: 'The Dead Rabbit',
    address: '30 Water St, New York, NY 10004',
    city: 'NYC',
    lat: 40.7033,
    lng: -74.0107,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/the-dead-rabbit',
    phone: '(646) 422-7906',
    website: 'https://www.deadrabbitnyc.com',
    rating: 4.5,
    priceLevel: '$$',
    dressCodeSummary: 'Casual',
    groupFriendly: true,
  },

  // BARS - SPORTS & GAMES
  {
    name: 'Spin New York',
    address: '48 E 23rd St, New York, NY 10010',
    city: 'NYC',
    lat: 40.7405,
    lng: -73.9881,
    bookingType: 'deeplink',
    bookingProvider: 'custom',
    bookingUrl: 'https://wearespin.com/venue/spin-newyork',
    phone: '(212) 982-8802',
    website: 'https://wearespin.com',
    rating: 4.4,
    priceLevel: '$$',
    dressCodeSummary: 'Casual',
    groupFriendly: true,
  },
  {
    name: 'Flight Club Darts',
    address: '44 W 28th St, New York, NY 10001',
    city: 'NYC',
    lat: 40.7463,
    lng: -73.9885,
    bookingType: 'deeplink',
    bookingProvider: 'custom',
    bookingUrl: 'https://flightclubdarts.com/new-york',
    phone: '(646) 762-1070',
    website: 'https://flightclubdarts.com',
    rating: 4.6,
    priceLevel: '$$',
    dressCodeSummary: 'Casual',
    groupFriendly: true,
  },
  {
    name: 'Brooklyn Bowl',
    address: '61 Wythe Ave, Brooklyn, NY 11249',
    city: 'NYC',
    lat: 40.7222,
    lng: -73.9576,
    bookingType: 'deeplink',
    bookingProvider: 'custom',
    bookingUrl: 'https://www.brooklynbowl.com',
    phone: '(718) 963-3369',
    website: 'https://www.brooklynbowl.com',
    rating: 4.4,
    priceLevel: '$$',
    dressCodeSummary: 'Casual',
    groupFriendly: true,
  },
  {
    name: 'Swindlers Cove',
    address: '157 W 47th St, New York, NY 10036',
    city: 'NYC',
    lat: 40.7586,
    lng: -73.9839,
    bookingType: 'manual',
    bookingProvider: null,
    bookingUrl: null,
    phone: '(212) 221-8440',
    website: 'https://www.swindlerscove.com',
    rating: 4.2,
    priceLevel: '$$',
    dressCodeSummary: 'Casual',
    groupFriendly: true,
  },
  {
    name: 'Two Bit\'s Retro Arcade',
    address: '153 Essex St, New York, NY 10002',
    city: 'NYC',
    lat: 40.7206,
    lng: -73.9876,
    bookingType: 'manual',
    bookingProvider: null,
    bookingUrl: null,
    phone: '(212) 477-2487',
    website: 'https://www.twobitsnyc.com',
    rating: 4.3,
    priceLevel: '$',
    dressCodeSummary: 'Casual',
    groupFriendly: true,
  },

  // ROOFTOP BARS
  {
    name: '230 Fifth Rooftop Bar',
    address: '230 5th Ave, New York, NY 10001',
    city: 'NYC',
    lat: 40.7442,
    lng: -73.9880,
    bookingType: 'deeplink',
    bookingProvider: 'custom',
    bookingUrl: 'https://www.230-fifth.com',
    phone: '(212) 725-4300',
    website: 'https://www.230-fifth.com',
    rating: 4.2,
    priceLevel: '$$$',
    dressCodeSummary: 'Smart casual',
    groupFriendly: true,
  },
  {
    name: 'The Press Lounge',
    address: '653 11th Ave, New York, NY 10019',
    city: 'NYC',
    lat: 40.7669,
    lng: -73.9952,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/the-press-lounge',
    phone: '(212) 757-2224',
    website: 'https://www.thepresslounge.com',
    rating: 4.3,
    priceLevel: '$$$',
    dressCodeSummary: 'Smart casual to business casual',
    groupFriendly: true,
  },
  {
    name: 'Westlight',
    address: '111 N 12th St, Brooklyn, NY 11249',
    city: 'NYC',
    lat: 40.7280,
    lng: -73.9578,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/westlight',
    phone: '(718) 307-7100',
    website: 'https://www.westlightnyc.com',
    rating: 4.5,
    priceLevel: '$$$',
    dressCodeSummary: 'Smart casual',
    groupFriendly: true,
  },
  {
    name: 'Magic Hour Rooftop Bar & Lounge',
    address: '485 7th Ave, New York, NY 10018',
    city: 'NYC',
    lat: 40.7542,
    lng: -73.9885,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/magic-hour',
    phone: '(212) 805-8220',
    website: 'https://www.magichournyc.com',
    rating: 4.3,
    priceLevel: '$$$',
    dressCodeSummary: 'Smart casual to dressy',
    groupFriendly: true,
  },
  {
    name: 'Le Bain',
    address: '848 Washington St, New York, NY 10014',
    city: 'NYC',
    lat: 40.7414,
    lng: -74.0068,
    bookingType: 'manual',
    bookingProvider: null,
    bookingUrl: null,
    phone: '(212) 645-7600',
    website: 'https://www.standardhotels.com/new-york/features/le-bain',
    rating: 4.4,
    priceLevel: '$$$',
    dressCodeSummary: 'Dressy / club attire',
    groupFriendly: true,
  },

  // CLUBS & LATE-NIGHT
  {
    name: 'Marquee New York',
    address: '289 10th Ave, New York, NY 10001',
    city: 'NYC',
    lat: 40.7509,
    lng: -74.0027,
    bookingType: 'manual',
    bookingProvider: null,
    bookingUrl: 'https://marqueeny.com',
    phone: '(646) 473-0202',
    website: 'https://marqueeny.com',
    rating: 4.1,
    priceLevel: '$$$$',
    dressCodeSummary: 'Upscale / nightclub attire',
    groupFriendly: true,
  },
  {
    name: 'LAVO New York',
    address: '39 E 58th St, New York, NY 10022',
    city: 'NYC',
    lat: 40.7628,
    lng: -73.9713,
    bookingType: 'deeplink',
    bookingProvider: 'custom',
    bookingUrl: 'https://lavonewyork.com',
    phone: '(212) 750-5588',
    website: 'https://lavonewyork.com',
    rating: 4.2,
    priceLevel: '$$$$',
    dressCodeSummary: 'Upscale / nightclub attire',
    groupFriendly: true,
  },
  {
    name: 'The Ainsworth',
    address: '122 W 26th St, New York, NY 10001',
    city: 'NYC',
    lat: 40.7450,
    lng: -73.9913,
    bookingType: 'api',
    bookingProvider: 'opentable',
    bookingUrl: 'https://www.opentable.com/r/the-ainsworth-chelsea-new-york',
    phone: '(212) 741-0645',
    website: 'https://www.theainsworth.com',
    rating: 4.0,
    priceLevel: '$$',
    dressCodeSummary: 'Casual to smart casual',
    groupFriendly: true,
  },

  // BRUNCH SPOTS
  {
    name: 'Balthazar',
    address: '80 Spring St, New York, NY 10012',
    city: 'NYC',
    lat: 40.7221,
    lng: -73.9973,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/balthazar',
    phone: '(212) 965-1414',
    website: 'https://www.balthazarny.com',
    rating: 4.4,
    priceLevel: '$$$',
    dressCodeSummary: 'Casual to smart casual',
    groupFriendly: true,
  },
  {
    name: 'Sarabeth\'s',
    address: '381 Park Ave S, New York, NY 10016',
    city: 'NYC',
    lat: 40.7435,
    lng: -73.9842,
    bookingType: 'api',
    bookingProvider: 'opentable',
    bookingUrl: 'https://www.opentable.com/r/sarabeths-park-avenue-south-new-york',
    phone: '(212) 335-0093',
    website: 'https://www.sarabeth.com',
    rating: 4.3,
    priceLevel: '$$',
    dressCodeSummary: 'Casual',
    groupFriendly: true,
  },
  {
    name: 'Jack\'s Wife Freda',
    address: '224 Lafayette St, New York, NY 10012',
    city: 'NYC',
    lat: 40.7252,
    lng: -73.9963,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/jacks-wife-freda',
    phone: '(212) 510-8550',
    website: 'https://jackswifefreda.com',
    rating: 4.4,
    priceLevel: '$$',
    dressCodeSummary: 'Casual',
    groupFriendly: true,
  },

  // UNIQUE EXPERIENCES
  {
    name: 'Sleep No More (McKittrick Hotel)',
    address: '530 W 27th St, New York, NY 10001',
    city: 'NYC',
    lat: 40.7517,
    lng: -74.0024,
    bookingType: 'deeplink',
    bookingProvider: 'custom',
    bookingUrl: 'https://mckittrickhotel.com/sleep-no-more',
    phone: '(212) 904-1880',
    website: 'https://mckittrickhotel.com',
    rating: 4.7,
    priceLevel: '$$$',
    dressCodeSummary: 'All black attire required',
    groupFriendly: true,
  },
  {
    name: 'The Museum of Ice Cream',
    address: '558 Broadway, New York, NY 10012',
    city: 'NYC',
    lat: 40.7239,
    lng: -73.9984,
    bookingType: 'deeplink',
    bookingProvider: 'custom',
    bookingUrl: 'https://www.museumoficecream.com',
    phone: '(855) 468-7326',
    website: 'https://www.museumoficecream.com',
    rating: 4.2,
    priceLevel: '$$',
    dressCodeSummary: 'Casual',
    groupFriendly: true,
  },
  {
    name: 'House of Yes',
    address: '2 Wyckoff Ave, Brooklyn, NY 11237',
    city: 'NYC',
    lat: 40.7053,
    lng: -73.9221,
    bookingType: 'deeplink',
    bookingProvider: 'custom',
    bookingUrl: 'https://www.houseofyes.org',
    phone: '(646) 838-4937',
    website: 'https://www.houseofyes.org',
    rating: 4.5,
    priceLevel: '$$',
    dressCodeSummary: 'Creative / costume encouraged',
    groupFriendly: true,
  },

  // CASUAL BARS & PUBS
  {
    name: 'McSorley\'s Old Ale House',
    address: '15 E 7th St, New York, NY 10003',
    city: 'NYC',
    lat: 40.7287,
    lng: -73.9882,
    bookingType: 'manual',
    bookingProvider: null,
    bookingUrl: null,
    phone: '(212) 473-9148',
    website: 'https://www.mcsorleysnewyork.com',
    rating: 4.3,
    priceLevel: '$',
    dressCodeSummary: 'Very casual',
    groupFriendly: true,
  },
  {
    name: 'The Stumble Inn',
    address: '1454 2nd Ave, New York, NY 10021',
    city: 'NYC',
    lat: 40.7714,
    lng: -73.9576,
    bookingType: 'manual',
    bookingProvider: null,
    bookingUrl: null,
    phone: '(212) 650-0561',
    website: null,
    rating: 4.1,
    priceLevel: '$',
    dressCodeSummary: 'Very casual',
    groupFriendly: true,
  },
  {
    name: 'Folly Bar',
    address: '92 W Houston St, New York, NY 10012',
    city: 'NYC',
    lat: 40.7268,
    lng: -74.0013,
    bookingType: 'manual',
    bookingProvider: null,
    bookingUrl: null,
    phone: '(212) 533-4500',
    website: 'https://www.follynyc.com',
    rating: 4.2,
    priceLevel: '$$',
    dressCodeSummary: 'Casual',
    groupFriendly: true,
  },
  {
    name: 'Rudy\'s Bar & Grill',
    address: '627 9th Ave, New York, NY 10036',
    city: 'NYC',
    lat: 40.7610,
    lng: -73.9911,
    bookingType: 'manual',
    bookingProvider: null,
    bookingUrl: null,
    phone: '(646) 707-0890',
    website: null,
    rating: 4.4,
    priceLevel: '$',
    dressCodeSummary: 'Very casual / dive bar',
    groupFriendly: true,
  },

  // WINE BARS
  {
    name: 'Terroir Tribeca',
    address: '24 Harrison St, New York, NY 10013',
    city: 'NYC',
    lat: 40.7183,
    lng: -74.0084,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/terroir-tribeca',
    phone: '(212) 625-9463',
    website: 'https://www.wineisterroir.com',
    rating: 4.4,
    priceLevel: '$$',
    dressCodeSummary: 'Casual to smart casual',
    groupFriendly: true,
  },
  {
    name: 'Compagnie des Vins Surnaturels',
    address: '249 Centre St, New York, NY 10013',
    city: 'NYC',
    lat: 40.7222,
    lng: -73.9980,
    bookingType: 'api',
    bookingProvider: 'resy',
    bookingUrl: 'https://resy.com/cities/ny/compagnie-des-vins-surnaturels',
    phone: '(212) 343-3660',
    website: 'https://www.compagniedesvinssurnaturels.com',
    rating: 4.5,
    priceLevel: '$$$',
    dressCodeSummary: 'Smart casual',
    groupFriendly: true,
  },

  // MEETUP SPOTS & CASUAL HANGOUTS
  {
    name: 'The Jane Hotel Ballroom',
    address: '113 Jane St, New York, NY 10014',
    city: 'NYC',
    lat: 40.7372,
    lng: -74.0098,
    bookingType: 'manual',
    bookingProvider: null,
    bookingUrl: null,
    phone: '(212) 924-6700',
    website: 'https://www.thejanenyc.com',
    rating: 4.3,
    priceLevel: '$$',
    dressCodeSummary: 'Casual to smart casual',
    groupFriendly: true,
  },
  {
    name: 'Pier i Cafe',
    address: 'Pier 17, 89 South St, New York, NY 10038',
    city: 'NYC',
    lat: 40.7068,
    lng: -74.0033,
    bookingType: 'manual',
    bookingProvider: null,
    bookingUrl: null,
    phone: null,
    website: 'https://www.pier17ny.com',
    rating: 4.1,
    priceLevel: '$$',
    dressCodeSummary: 'Casual',
    groupFriendly: true,
  },
  {
    name: 'The Highline Hotel Bar',
    address: '180 10th Ave, New York, NY 10011',
    city: 'NYC',
    lat: 40.7461,
    lng: -74.0059,
    bookingType: 'manual',
    bookingProvider: null,
    bookingUrl: null,
    phone: '(212) 929-3888',
    website: 'https://www.thehighlinehotel.com',
    rating: 4.2,
    priceLevel: '$$',
    dressCodeSummary: 'Casual to smart casual',
    groupFriendly: true,
  },
];

async function seedVenues() {
  console.log('🌱 Starting venue seed...');

  let created = 0;
  let skipped = 0;

  for (const venue of NYC_VENUES) {
    try {
      const existing = await prisma.venue.findFirst({
        where: {
          name: venue.name,
          city: venue.city,
        },
      });

      if (existing) {
        console.log(`⏭️  Skipping existing venue: ${venue.name}`);
        skipped++;
        continue;
      }

      await prisma.venue.create({
        data: venue,
      });

      console.log(`✅ Created venue: ${venue.name}`);
      created++;
    } catch (error) {
      console.error(`❌ Error creating venue ${venue.name}:`, error);
    }
  }

  console.log(`\n✨ Venue seed complete!`);
  console.log(`Created: ${created}`);
  console.log(`Skipped: ${skipped}`);
  console.log(`Total venues in seed: ${NYC_VENUES.length}`);
}

seedVenues()
  .catch((error) => {
    console.error('Seed failed:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
